### ISSUE TITLE
Why are there multiple versions of some scripts?

### ISSUE THREAD

**Issue by IsibisiDev** [cferdinandi/go-make-things#2]
I've noticed that some scripts have different versions, which one is the right one to consider?

List below some pairs of similar scripts:

1. https://gomakethings.com/how-to-get-all-parent-elements-with-vanilla-javascript/
2. https://vanillajstoolkit.com/helpers/getparents/
---------
1. https://gomakethings.com/climbing-the-dom-until-you-get-a-match-using-native-javascript/ && https://gomakethings.com/climbing-up-the-dom-until-you-hit-a-match-with-vanilla-javascript/
2. https://vanillajstoolkit.com/helpers/getparentsuntil/

**Comment by cferdinandi** [comment]
Since I write I daily, I periodically revisit topics. When in doubt:

1. The version on the Vanilla JS Toolkit is the "official" version that I personally use in my projects.
2. If there's no version in the toolkit, the article with the newest date is typically the more up-to-date version.
