### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by yowainwright** [cferdinandi/go-make-things#7]
Hey, @cferdinandi! 

I'm a _fairly_ long-time follower of your work!

I always love your perspective on coding. 
Often, your newsletter provides a unique way of thinking about building webpages—more of a focus on plain JavaScript, CSS, and HTML. 

Have you considered creating a sponsor link on Github? 

I'd love to sponsor your work more!

Thank you!

Jeff

P.S. I understand you'll close this issue when you see it/read it most likely—no issue etiquette needed! 😄

**Comment by cferdinandi** [comment]
Hi there! Thanks for the kind words! No sponsorships. My income comes mostly from product sales. But thank you!
